package com.example.photobooth.screens

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Button
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.unit.dp
import com.google.zxing.BarcodeFormat
import com.google.zxing.qrcode.QRCodeWriter
import android.graphics.Bitmap

/**
 * downloadUrl is the signed Firebase Storage link generated by the
 * onPhotoUploaded Cloud Function -- we render it as a QR client-side with ZXing.
 *
 * TODO: add app/build.gradle dependency:  implementation "com.google.zxing:core:3.5.3"
 * TODO: in production, auto-reset to Idle after ~20-30s of inactivity
 * instead of relying only on the button.
 */
@Composable
fun DownloadScreen(downloadUrl: String, onDone: () -> Unit) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Text(text = "Scan to download your photo")

        val qrBitmap = remember(downloadUrl) { generateQrBitmap(downloadUrl, 512) }
        if (qrBitmap != null) {
            Image(
                bitmap = qrBitmap.asImageBitmap(),
                contentDescription = "Download QR code",
                modifier = Modifier.size(260.dp)
            )
        }

        Button(onClick = onDone) {
            Text("Done - next customer")
        }
    }
}

private fun generateQrBitmap(content: String, size: Int): Bitmap? = runCatching {
    val bitMatrix = QRCodeWriter().encode(content, BarcodeFormat.QR_CODE, size, size)
    val bitmap = Bitmap.createBitmap(size, size, Bitmap.Config.RGB_565)
    for (x in 0 until size) {
        for (y in 0 until size) {
            bitmap.setPixel(x, y, if (bitMatrix[x, y]) 0xFF000000.toInt() else 0xFFFFFFFF.toInt())
        }
    }
    bitmap
}.getOrNull()
